version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ai-dd-agent-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: